path: E:\ORC_mobile_app\newTrain\data
train: train/images
val: valid/images
test: test/images

nc: 7
names:
  0: batch
  1: cardnumber
  2: cost
  3: datetime
  4: namecustomer
  5: namemerchine
  6: typecard
